# Generated by Django 3.2.18 on 2023-04-11 18:53

from django.db import migrations, models
import django.db.models.deletion
import pretix.base.models.base
import pretix_attendance_certificate.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pretixbase", "0235_auto_20230316_2023"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceCertificateLayout",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("default", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=190)),
                (
                    "layout",
                    models.TextField(
                        default='[{"type":"textarea","left":"13.09","bottom":"49.73","fontsize":"23.6","color":[0,0,0,1],"fontfamily":"Open Sans","bold":true,"italic":false,"width":"121.83","content":"attendee_name","text":"Marco","align":"center"}]'  # noqa
                    ),
                ),
                (
                    "background",
                    models.FileField(
                        max_length=255,
                        null=True,
                        upload_to=pretix_attendance_certificate.models.bg_name,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_certificate_layouts",
                        to="pretixbase.event",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, pretix.base.models.base.LoggingMixin),
        ),
    ]
